# Generated by Django 5.2.5 on 2025-09-01 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бонус за обучение')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_received', to=settings.AUTH_USER_MODEL, verbose_name='Обучаемый')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_given', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
        ),
    ]
