# Generated by Django 5.2.5 on 2025-09-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex', 'Яндекс.Маркет'), ('other', 'Другое')], max_length=50, verbose_name='Тип пункта')),
            ],
        ),
    ]
