# Generated by Django 5.2.5 on 2025-09-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined_work',
            field=models.DateField(default=datetime.datetime(2025, 9, 1, 13, 35, 40, 98429), verbose_name='Дата зачисления на работу'),
        ),
    ]
