# Generated by Django 5.2.5 on 2025-09-01 10:38

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_user_date_joined_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined_work',
            field=models.DateField(default=django.db.models.functions.datetime.Now(), verbose_name='Дата зачисления на работу'),
        ),
    ]
