# Generated by Django 5.2.5 on 2025-09-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickup_points', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время штрафа')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('claim_number', models.CharField(max_length=50, verbose_name='Номер претензии')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма штрафа')),
                ('status', models.CharField(choices=[('counted', 'Учитывается'), ('disputed', 'Оспорен'), ('pending', 'На проверке')], default='pending', max_length=20, verbose_name='Статус')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickup_points.pickuppoint', verbose_name='Пункт выдачи')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
